# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bundler'
Bundler.require

module Kernel
  def motion_require(file)
    Motion::Require.all([file])
  end
end

require '../../lib/motion-support/inflector'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Inflector'
  app.detect_dependencies = false
end
